### ISSUE TITLE
Wrong Value DS3 2

### ISSUE THREAD

**Issue by peter33826** [patience4711/RPI-APS-inverters#45]
Hi,
I use DS3-S EU (limited to 600W) and 2 module (400W each) and software version 2.7.
![PV_bug](https://user-images.githubusercontent.com/45110031/173425442-835e0b70-ddff-4a2f-a8e3-5263d93541e6.jpg)

(one module is limited to 400W, DS3 is limited to 600W so the values seem too high)

![PV_bug2](https://user-images.githubusercontent.com/45110031/173425469-7537dad5-446b-4ccc-a11f-12d36e7d4481.jpg)

Loosing all energy wh values. 
It seems, that something is wrong with the values. Does someone know how to fix?
Thanks.

**Comment by patience4711** [comment]
There was a small bug in the time extraction from the inverter. That leads to miscalculations. 
It should be fixed now you can upgrade to 2_8
Be sure you registered the right invertertype.

**Comment by peter33826** [comment]
Thanks for fast reponse. I tested version 2.8
![PV_bug3](https://user-images.githubusercontent.com/45110031/173554005-67a55250-ac9e-4c71-a322-5b317fb0153b.jpg)
This looks better.

But there is still a problem in the power calculation:
![PV_bug5](https://user-images.githubusercontent.com/45110031/173554146-00c7e624-2682-4541-93ff-f36ff5aa807f.jpg)

![PV_bug4](https://user-images.githubusercontent.com/45110031/173555786-e2563a8a-1581-43dd-ba62-ceb28d18a7e0.jpg)

The power calculation does not seem to be correct.
34,5V x 0,5A = 17,25W != 0,2W
37,2V x 0,2A = 7,44W != 0,1W

**Comment by patience4711** [comment]
Now the energy increases seem allright but the power isn't calculated correctly.
If you manually poll, the results appear in the console. Can you make a screenshot of that?
I can debug it then.

**Comment by patience4711** [comment]
I found the error already
If you download and install the file ecu_swupdate_14-06-2022.tar below, it will work as it should.
[ ecu_swupdate_14-06-2022.tar](https://1drv.ms/u/s!AkMG5FvUwhedi0w0itFjZ4A_Jc-n?e=bhabdM)

please note that this is still version 2_8

**Comment by peter33826** [comment]
Now it is ok. Thanks a lot for fast fixing.
